Simplifiy np deps
AllenNeuralDynamics/aind-metadata-mapper pull request #174
Opened 2024-09-25 00:18 UTC by rcpeene

refactor code to remove npc_sessions and np_session dependencies

2024-09-26 00:30 UTC, jtyoung84 commented on src/aind_metadata_mapper/stimulus/camstim.py
> +NPEXP_ROOT = Path("//allen/programs/mindscope/workgroups/np-exp")
It's not recommended to hard-code endpoints. It'll be better to make this configurable.

2024-09-26 00:31 UTC, jtyoung84 commented on src/aind_metadata_mapper/stimulus/camstim.py
> +        server = "http://mtrain:5000"
Same comment as above: It's not recommended to hard-code endpoints. It'll be better to make this configurable.

2024-09-26 00:39 UTC, jtyoung84 commented on src/aind_metadata_mapper/open_ephys/camstim_ephys_session.py
> +    def run_job(self):
The run_job should return a JobResponse type. You can probably call the GenericEtl _load method instead of overwriting it.

2024-09-26 00:40 UTC, jtyoung84 reviewed
The airflow service uses this as the entrypoint to run session etl jobs: https://github.com/AllenNeuralDynamics/aind-metadata-mapper/blob/a4f617ac162c888f59d527ec412ee1161721f98a/src/aind_metadata_mapper/gather_metadata.py#L279

2024-10-01 20:29 UTC, mekhlakapoor commented on src/aind_metadata_mapper/open_ephys/camstim_ephys_session.py
>  import npc_mvr
Add this to the pyproject.toml with a lower bound if necessary/python pin

2024-10-01 20:31 UTC, mekhlakapoor commented on src/aind_metadata_mapper/open_ephys/models.py
> +    sessions_root: Union[Path, str] = \
avoid hardcoding endpoints/locations. sessions_root and mtrain_server should be defined by the user when creating Jobsettings rather than in the code

2024-10-01 20:31 UTC, mekhlakapoor commented on src/aind_metadata_mapper/open_ephys/models.py
> +    mouse_platform_name: str = "disc"
there are 2 mouse_platform_name : 'Mouse Platform' and 'disck' which one's the correct one?

2024-10-01 20:33 UTC, mekhlakapoor requested changes

2024-10-01 20:33 UTC, mekhlakapoor commented on src/aind_metadata_mapper/open_ephys/camstim_ephys_session.py
> +class CamstimEphysSession(
re-name to "CamstimEphysSessionEtl"

2024-10-02 20:53 UTC, mekhlakapoor approved these changes

2024-10-02 20:53 UTC, merged