add check for behavior/ophys session
AllenNeuralDynamics/aind-metadata-mapper pull request #77
Opened 2024-06-25 17:51 UTC by Ahad-Allen

2024-07-08 21:26 UTC, mekhlakapoor requested changes
Instead of try/except block, we can use `in` to be more concise:

`return 'behavior' in pkl["items"]`

2024-07-08 23:21 UTC, arielleleon requested changes

2024-07-08 23:21 UTC, arielleleon commented on src/aind_metadata_mapper/stimulus/camstim.py
> +                self.build_behavior_table()
behavior_utils is missing from this repository unless I am missing something https://github.com/AllenNeuralDynamics/aind-metadata-mapper/blob/723d5237ece5b680be0d5f57f799e96478a053e0/src/aind_metadata_mapper/stimulus/camstim.py#L20

2024-10-31 17:53 UTC, closed without merging

2024-10-31 17:53 UTC, arielleleon commented
Closing - I have all of @Ahad-Allen's changes in another branch